name: FriendsPlus
main: me.codingcookie.friendsplus.FriendsPlus
version: 0.0.2
description: Add friends!
authors: [CodingCookie]

commands:
  friends:
    description: Check, add, or remove friends.
    aliases: [friends, friend, f]
  addfriend:
    description: Add new friends!
    aliases: [af, addfriends, afriend]
  rejectfriend:
    description: Reject friend requests.
    aliases: [rf, rejectfriends, rfriend]

permissions:
  friendsplus.*:
    description: Grants access to all FriendsPlus commands.

